# Generated by Django 3.2.9 on 2021-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211201_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, default='I_Am_Flow', max_length=50, null=True),
        ),
    ]
